var get_lang = function (lang) {
    var lang_arr_en = {
        t: 'en',

        categoryFilms: 'Films',
        categorySerials: 'Serials',
        categoryAnime: 'Anime',
        categoryDocHum: 'Doc. and humor',
        categoryMusic: 'Music',
        categoryGames: 'Games',
        categoryBooks: 'Books',
        categoryCartoons: 'Cartoons',
        categorySoft: 'Software',
        categorySport: 'Sport',
        categoryXXX: 'XXX',
        categoryOther: 'Other',

        cat_all: 'All',
        btn_form: 'Search',
        btn_main: 'Main',
        btn_history: 'Search history',
        btn_up: 'Up!',
        tracker_list: 'Trackers',
        btn_tracker_list: 'Setup',
        filter: 'Word filter',
        btn_filter: 'Clear',
        size_filter: 'Size filter',
        size_filter_f: 'from',
        size_filter_t: 'to',
        size_filter_g: 'Gb',

        columnTime: 'Date',
        columnQualityShort: 'Q',
        columnQuality: 'Quality',
        columnTitle: 'Title',
        columnSize: 'Size',
        columnSeedsShort: 'S',
        columnSeeds: 'Seeders',
        columnLeechsShort: 'P',
        columnLeechs: 'Peers',

        btn_login: 'Login',
        size_list: '["b","Kb","Mb","Gb","Tb","Pb","Eb","Zb","Yb"]',

        time_yest: 'Yesterday',
        time_today: 'Today',
        time_week1: 'week',
        time_week2: 'week',
        time_week3: 'weeks',
        time_week4: 'week',
        time_day1: 'day',
        time_day2: 'day',
        time_day3: 'days',
        time_day4: 'day',
        time_hour1: 'hour',
        time_hour2: 'hour',
        time_hour3: 'hours',
        time_hour4: 'hour',
        time_min: 'min.',
        time_sec: 'sec',
        time_old: 'ago',

        exp_btn_sync: 'Update',
        exp_btn_open: 'Open site',

        exp_items_favorites: 'Favorites',
        exp_items_kp_favorites: 'Kinopoisk: Favorites',
        exp_items_kp_in_cinema: 'Now in the movie',
        exp_items_kp_popular: 'Movies',
        exp_items_kp_serials: 'TV Series',
        exp_items_imdb_in_cinema: 'IMDB: Now in the movie',
        exp_items_imdb_popular: 'IMDB: Movies',
        exp_items_imdb_serials: 'IMDB: TV Series',
        exp_items_gg_games_top: 'Games: Best',
        exp_items_gg_games_new: 'Games: New',

        exp_setup_view: 'Setup view',
        exp_in_fav: 'Add to favorites',
        exp_rm_fav: 'Remove from favorites',
        exp_edit_fav: 'Edit poster',
        exp_move_fav: 'Move poster',
        exp_edit_fav_label0: 'Enter new name',
        exp_edit_fav_label1: 'Image url',
        exp_edit_fav_label2: 'Description url',
        exp_more: 'More',
        exp_default: 'Default',
        his_title: 'Search history',
        his_h1: 'History',
        his_no_his: 'The search history yet',
        his_rm_btn: 'Remove',
        stp_title: 'Search setup',
        stp_setup: 'Setup',
        stp_save_btn: 'Save',
        stp_legend_1: 'Trackers',
        stp_legend_7: 'Options',
        stp_legend_16: 'Filters the list',
        stp_th_2: 'Torrent tracker',
        stp_th_3: 'Description',
        stp_th_4: 'On',
        stp_th_5: 'Off',
        stp_th_6: 'Default',
        stp_span_8: 'Show icons torrent trackers in search results',
        stp_span_9: 'Hide torrents without seeders (distributed)',
        stp_span_10: 'Hide column leechers (downloaders)',
        stp_span_11: 'Hide column seeders (distributed)',
        stp_span_12: 'Automatically move to the category when your choice movie/series etc in the main page',
        stp_span_13: 'Do not show teasers/trailers in search results',
        stp_span_14: 'Add a quick search in the address bar (write "tms" then press Tab)',
        stp_span_15: 'Add search in the context menu',
        stp_span_17: 'Seeking complete coincidence phrases (more than 1 phrases may be separated by commas.)',
        stp_span_18: 'Seeking coincidence with one from entered words',
        stp_span_19: 'Seeking coincidence all entered words',
        stp_legend_20: 'Language',
        stp_opt_21: 'Russian',
        stp_opt_22: 'English',
        stp_opt_23: 'Show search popup, when you click on extension icon',
        y_money: 'Yandex Money',
        donate: 'Donate me!',
        ctx_title: 'Search torrent',
        label_profile: 'Profile',
        label_def_profile: 'Default',
        spn_26: 'Title',
        btn_25: 'Remove',
        btn_27: 'Add',
        exp_q_fav: 'Get quality',

        flag_cirilic: 'Unsupport cyrillic',
        flag_auth: 'Requires authorization',
        flag_rus: 'Russian language tracker',
        flag_proxy: 'Search via proxy',

        stp_span_24: 'Enable AutoComplete from Google',
        stp_legend_25: 'Other',
        stp_span_34: 'Receive posters, on the home page via a proxy bt google (images-pos-opensocial) (experiment)',
        stp_span_27: 'Disable Google-Analytics',
        str28: 'Export settings',
        str29: 'Backup',
        str30: 'Restore',
        str31: 'Update',
        str32: 'Restore',
        str33: 'Restore error!',
        exp_source: 'Source',
        exp_s_a_f: 'movies',
        exp_s_a_g: 'games',
        str_subsategoryfilter: 'Consider subcategories',
        str_autosetcat: 'Define the category of the torrent, if it is not present',
        ad: 'Ad',
        use_english_postername: 'Show names movie\\series in English on the front page',
        allow_get_description: 'Get a description of the search query from Google. (each request will be matched with google!)',
        allow_favorites_sync: 'Allow sync favorites list in the cloud',
        clear_cloud_btn: 'Clear settings in the cloud',
        apprise_btns0: 'Ok',
        apprise_btns1: 'Cancel',
        time_filter: 'Date filter',

        time_f_s_all:'For all the time',
        time_f_s_1h:'For an hour',
        time_f_s_24h:'For the day',
        time_f_s_72h:'For the 3 day',
        time_f_s_1w:'For the week',
        time_f_s_1m:'For the month',
        time_f_s_1y:'For the year',
        time_f_s_range:'For the period...',

        time_f_d: '["su","mo","tu","we","th","fr","sa"]',
        time_f_m: '["January","February","March","April","May","June","July","August","September","October","November","December"]',

        seed_filter: "Seeds",
        peer_filter: "Peers",
        settings_saved: "Saved!",
        trackerNotFound: "Tracker not found!",
        findNotFound: "To find!",
        feedback: 'Feedback',
        settings: {
            1: "The list of torrents",
            2: "Options",
            3: "Restoring settings",
            4: "Language",
            5: "Lists of torrents",
            6: "Remove",
            7: "Add",
            8: "Torrent trackers",
            9: "Torrent tracker",
            10: "Description",
            11: "On",
            12: "Off",
            13: "Default",
            14: "Advanced settings",
            15: "Show icons torrent trackers in search results",
            16: "Hide torrents without seeders (distributed)",
            17: "Hide column leechers (downloaders)",
            18: "Hide column seeders (distributed)",
            19: "Automatically move to the category when your choice movie/series etc in the main page",
            20: "Enable autoсomplete from Google",
            21: "Do not show teasers\\trailers in search results",
            23: "Add search in the context menu",
            24: "Show search popup, when you click on extension icon",
            25: "Try define the category of the torrent, if it is not present",
            26: "Show names movie\\series in English",
            27: "Get a description of the search query from Google. (Every request will search in google!)",
            28: "Allow sync favorites list in the cloud",
            29: "Filters the list",
            30: "Seeking complete coincidence phrases (more than 1 phrases may be separated by commas.)",
            31: "Seeking coincidence with one from entered words",
            32: "Seeking coincidence all entered words",
            33: "Consider subcategories",
            34: "Other",
            35: "Receive posters, on the home page via a proxy google (images-pos-opensocial) (experiment)",
            36: "Disable Google-Analytics",
            37: "Backup and restore settings",
            38: "Backup",
            39: "Restore",
            40: "",
            41: "Update",
            42: "",
            43: "Restore",
            44: "Clear settings in the cloud",
            45: "Save all!",
            46: "If possible please",
            47: " make a donation through",
            48: "or",
            49: "Yndex.Money",
            50: "Name",
            51: "There's nothing yet",
            52: "Edit",
            53: "Delete",
            54: "This code has already been added.",
            55: "Loading error!",
            56: "Error",
            57: "Tools",
            58: "Management of user torrent trackers",
            59: "Add the torrent code",
            60: "Create",
            61: "Tracker code",
            62: "Add",
            63: "Edit",
            64: "Close",
            65: "Custom codes torrent trackers posted",
            66: "on this site",
            67: "Highlight the notes in the name of the torrent",
            68: "Save the settings to the cloud",
            69: "Get the settings from the cloud",
            70: "Saved!",
            71: "Show favorites from the site kinopoisk.",
            72: "ID \"category\" from the site kinopoisk (1 - favorites)",
            73: "Action",
            74: "Move the filter panel to the left",
            75: "Hide Top-40 search query",
            76: "Main page",
            77: "Show sections:",
            78: "Don't to open a new page when click download link ↓",
            79: "Disable animation links",
            80: "Disable all animations",
            81: "Allow synchronization of the list of trackers (custom trackers must add it manually)",
            82: 'Proxy work only for GET search request and HTTP protocol!',
            83: 'Proxy url',
            84: 'Escape white spaces'
        },
        magic_1: 'Loading error!',
        magic_2: "Search",
        magic_3: "Selectors",
        magic_4: "Convert",
        magic_5: "Authorization",
        magic_6: "Description",
        magic_7: "Get \\ Read code",
        magic_8: "Search results",
        magic_9: "The URL of the search results page",
        magic_10: "Open",
        magic_11: "The search request (query parameter using the variable %search%)",
        magic_12: "Convert Cyrillic in cp1251",
        magic_13: "POST request",
        magic_14: "Root url",
        magic_15: "Defining the login page",
        magic_16: "The URL of the login page",
        magic_17: "Open",
        magic_18: "Login form",
        magic_19: "Choose",
        magic_20: "Selectors",
        magic_21: "Row in a table",
        magic_22: "Name of category",
        magic_23: "Link to the category",
        magic_24: "Add the root url",
        magic_25: "The name of the torrent",
        magic_26: "Link to to the torrent-page",
        magic_27: "Add the root url",
        magic_28: "Torrent size",
        magic_29: "Torrent download link",
        magic_30: "Add the root url",
        magic_31: "Number of seeders",
        magic_32: "Number of peers",
        magic_33: "Torrent date",
        magic_34: "Skip the first n rows",
        magic_35: "Skip the last n rows",
        magic_36: "Convert",
        magic_37: "Torrent date",
        magic_38: "Apply regexp",
        magic_39: "replace to",
        magic_40: "Replace the name of the month by the number of",
        magic_41: "Convert time in Unix timestamp format from",
        magic_42: "The original string",
        magic_43: "Converted",
        magic_44: "Result",
        magic_45: "Torrent size",
        magic_46: "Convert",
        magic_47: "The original string",
        magic_48: "Converted",
        magic_49: "Description of the torrent tracker",
        magic_50: "base64 icon (16x16px)",
        magic_51: "Torrent name",
        magic_52: "Torrent description",
        magic_53: "Cyrillic support",
        magic_54: "Login required",
        magic_55: "Russian language tracker",
        magic_56: "Get \\ Read code",
        magic_57: "Get the code",
        magic_58: "Read the code",
        magic_59: "Seeds",
        magic_60: "Peers",
        magic_61: "Table",
        magic_62: "Attribute",
        magic_63: "Replace the words of today\\yesterday\\now",
        magic_64: "Page charset"
    };
    var lang_arr_ru = {
        t: 'ru',

        categoryFilms: 'Фильмы',
        categorySerials: 'Сериалы',
        categoryAnime: 'Анимэ',
        categoryDocHum: 'Док. и юмор',
        categoryMusic: 'Музыка',
        categoryGames: 'Игры',
        categoryBooks: 'Книги',
        categoryCartoons: 'Мультфильмы',
        categorySoft: 'ПО',
        categorySport: 'Спорт',
        categoryXXX: 'XXX',
        categoryOther: 'Прочее',

        cat_all: 'Всё',
        btn_form: 'Найти',
        btn_main: 'Главная',
        btn_history: 'История поиска',
        btn_up: 'Вверх!',
        tracker_list: 'Трекеры',
        btn_tracker_list: 'Настройки',
        filter: 'Фильтр слов',
        btn_filter: 'Очистить',
        size_filter: 'Размер',
        size_filter_f: 'от',
        size_filter_t: 'до',
        size_filter_g: 'Гб',

        columnTime: 'Добавлено',
        columnQualityShort: 'К',
        columnQuality: 'Качество',
        columnTitle: 'Название',
        columnSize: 'Размер',
        columnSeedsShort: 'С',
        columnSeeds: 'Раздают',
        columnLeechsShort: 'Л',
        columnLeechs: 'Скачивают',

        btn_login: 'Войти',
        size_list: '["б","Кб","Мб","Гб","Тб","Пб","Eb","Zb","Yb"]',


        time_yest: 'Вчера',
        time_today: 'Сегодня',
        time_week1: 'недель',
        time_week2: 'неделя',
        time_week3: 'недели',
        time_week4: 'недель',
        time_day1: 'дней',
        time_day2: 'день',
        time_day3: 'дня',
        time_day4: 'дней',
        time_hour1: 'часов',
        time_hour2: 'час',
        time_hour3: 'часа',
        time_hour4: 'часов',
        time_min: 'мин.',
        time_sec: 'сек',
        time_old: 'назад',

        exp_btn_sync: 'Обновить',
        exp_btn_open: 'Перейти на сайт',

        exp_items_favorites: 'Избранное',
        exp_items_kp_favorites: 'Кинопоиск: Избранное',
        exp_items_kp_in_cinema: 'Сейчас в кино',
        exp_items_kp_popular: 'Фильмы',
        exp_items_kp_serials: 'Сериалы',
        exp_items_imdb_in_cinema: 'IMDB: Сейчас в кино',
        exp_items_imdb_popular: 'IMDB: Фильмы',
        exp_items_imdb_serials: 'IMDB: Сериалы',
        exp_items_gg_games_top: 'Игры: Лучшие',
        exp_items_gg_games_new: 'Игры: Новые',

        exp_setup_view: 'Настроить вид',
        exp_in_fav: 'В избранное',
        exp_rm_fav: 'Удалить из избранного',
        exp_edit_fav: 'Редактировать постер',
        exp_move_fav: 'Переместить',

        exp_edit_fav_label0: 'Введите новое имя',
        exp_edit_fav_label1: 'URL изображения',
        exp_edit_fav_label2: 'URL описания',

        exp_more: 'Подробнее',
        exp_default: 'По умолчанию',
        his_title: 'История поиска',
        his_h1: 'История',
        his_no_his: 'Истории поиска пока нет',
        his_rm_btn: 'Удалить',
        stp_title: 'Настройки поиска',
        stp_setup: 'Настройки',
        stp_save_btn: 'Сохранить',
        stp_legend_1: 'Трекеры',
        stp_legend_7: 'Опции',
        stp_legend_16: 'Фильтрация списка',
        stp_th_2: 'Торрент трекер',
        stp_th_3: 'Описание',
        stp_th_4: 'Вкл',
        stp_th_5: 'Выкл',
        stp_th_6: 'Станд.',
        stp_span_8: 'Показывать иконки торрент-трекеров в результатах поиска',
        stp_span_9: 'Скрывать раздачи без сидеров (раздающих)',
        stp_span_10: 'Скрыть столбец личеров (скачивающих)',
        stp_span_11: 'Скрыть столбец сидов (раздающих)',
        stp_span_12: 'Автоматически переходить в соотв. категорию при выборе фильма/сериала итп на главной',
        stp_span_13: 'Не показывать тизеры\\трейлеры в результатах поиска',
        stp_span_14: 'Добавить быстрый поиск в строку адреса (пишем tms потом жмем Tab)',
        stp_span_15: 'Добавить поиск в контекстное меню',
        stp_span_17: 'Ищет полное совпадение фразы (более 1 фразы можно разделить запятой)',
        stp_span_18: 'Ищет совпадение с одним из введенных слов',
        stp_span_19: 'Ищет совпадение всех введенных слов',
        stp_legend_20: 'Язык / Language',
        stp_opt_21: 'Русский',
        stp_opt_22: 'English',
        stp_opt_23: 'Показывать поиск при нажатии на иконку расширения',
        y_money: 'Яндекс Деньги',
        donate: 'На жвачку!',
        ctx_title: 'Найти торрент',
        label_profile: 'Профиль',
        label_def_profile: 'Стандартный',
        spn_26: 'Название',
        btn_25: 'Удалить',
        btn_27: 'Добавить',
        exp_q_fav: 'Узнать качество',

        flag_cirilic: 'Не поддерживает кириллицу',
        flag_auth: 'Требуется авторизация',
        flag_rus: 'Русскоязычный трекер',
        flag_proxy: 'Искать через proxy',

        stp_span_24: 'Включить автозаполнение от Google',
        stp_legend_25: 'Прочее',
        stp_span_34: 'Получать постеры, на главной странице, через прокси гугла (images-pos-opensocial) (эксперимент)',
        stp_span_27: 'Отключить Google-Analytics',
        str28: 'Экспорт настроек',
        str29: 'Бэкап',
        str30: 'Восстановление',
        str31: 'Обновить',
        str32: 'Восстановить',
        str33: 'Ошибка восстановления настроек!',
        exp_source: 'Источники',
        exp_s_a_f: 'фильмы',
        exp_s_a_g: 'игры',
        str_subsategoryfilter: 'Учитывать подкатегории',
        str_autosetcat: 'Определить категорию раздачи, если её нету',
        ad: 'Реклама',
        use_english_postername: 'Отображать имена фильмов\\сериалов на английском на главной странице',
        allow_get_description: 'Получать описание поискового запроса из Google. (каждый запрос будет искаться в google!)',
        allow_favorites_sync: 'Разрешить синхронизацию списка избранного в облако',
        clear_cloud_btn: 'Очистить настройки в облаке',
        apprise_btns0: 'Готово',
        apprise_btns1: 'Отменить',
        time_filter: 'Дата',

        time_f_s_all:'За всё время',
        time_f_s_1h:'За час',
        time_f_s_24h:'За сутки',
        time_f_s_72h:'За 3-е суток',
        time_f_s_1w:'За неделю',
        time_f_s_1m:'За месяц',
        time_f_s_1y:'За год',
        time_f_s_range:'За период...',

        time_f_d: '["вс","пн","вт","ср","чт","пт","сб"]',
        time_f_m: '["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"]',

        seed_filter: "Сиды",
        peer_filter: "Пиры",
        settings_saved: "Сохранено!",
        trackerNotFound: "Трекер не найден!",
        findNotFound: "Найти!",
        feedback: 'Сообщить о проблеме...',
        settings: {
            1: "Список торрентов",
            2: "Опции",
            3: "Восст. наcтроек",
            4: "Язык / Language",
            5: "Списки торрентов",
            6: "Удалить",
            7: "Добавить",
            8: "Торрент трекеры",
            9: "Торрент трекер",
            10: "Описание",
            11: "Вкл",
            12: "Выкл",
            13: "Станд",
            14: "Дополнительные настройки",
            15: "Показывать иконки торрент-трекеров в выдаче",
            16: "Скрывать раздачи без сидеров (раздающих)",
            17: "Скрыть столбец личеров (скачивающих)",
            18: "Скрыть столбец сидов (раздающих)",
            19: "Автоматически переходить в соотв. категорию при выборе фильма\\сериала итп на главной",
            20: "Включить автозаполнение от Google",
            21: "Не показывать тизеры\\трейлеры в результатах поиска",
            23: "Добавить поиск в контекстное меню",
            24: "Показывать поиск при нажатии на иконку расширения",
            25: "Автоматически определить категорию раздачи",
            26: "Отображать имена фильмов\\сериалов на английском",
            27: "Получать описание поискового запроса из Google. (каждый запрос будет искаться в google!)",
            28: "Разрешить синхронизацию списка избранного",
            29: "Фильтрация списка",
            30: "Ищет полное совпадение фразы (более 1 фразы можно разделить запятой)",
            31: "Ищет совпадение с одним из введенных слов",
            32: "Ищет совпадение всех введенных слов",
            33: "Учитывать подкатегории",
            34: "Прочие",
            35: "Получать постеры на главной странице через прокси гугла (images-pos-opensocial)",
            36: "Отключить Google-Analytics",
            37: "Разервное копирование и восстановление настроек",
            38: "Бэкап",
            39: "Восстановление",
            40: "",
            41: "Обновить",
            42: "",
            43: "Восстановить",
            44: "Очистить настройки в облаке",
            45: "Сохранить все!",
            46: "Если возможно, пожалуйста",
            47: ", сделайте пожертвование через",
            48: "или",
            49: "Яндекс.Деньги",
            50: "Название",
            51: "Тут пока ничего нету",
            52: "Изменить",
            53: "Удалить",
            54: "Этот код уже добавлен.",
            55: "Ошибка загрузки!",
            56: "Ошибка",
            57: "Инструменты",
            58: "Управление пользовательскими торрент-трекерами",
            59: "Добавить код торрента",
            60: "Создать",
            61: "Код трекера",
            62: "Добавить",
            63: "Изменить",
            64: "Закрыть",
            65: "Пользовательские коды торрент трекеров выложены",
            66: "на этом сайте",
            67: "Подсвечивать пояснения в названии раздачи",
            68: "Сохранить настройки в облако",
            69: "Получить из облака",
            70: "Сохранено!",
            71: "Показывать избранное с сайта кинопоиска.",
            72: "ID \"категории\" из кинопоиска (1 - избранное)",
            73: "Действие",
            74: "Переместить панель фильтров влево",
            75: "Скрыть Топ-40 поисковых запросов",
            76: "Главная страница",
            77: "Показывать секции:",
            78: "Не открывать новую страницу при нажатии на ссылку загрузки ↓",
            79: "Отключить анимацию ссылок",
            80: "Отключить всю анимацию",
            81: "Разрешить синхронизацию списка трекеров (пользовательские трекеры нужно добавлять вручную)",
            82: 'Proxy работает только для GET запросов и HTTP протокола!',
            83: 'Proxy url',
            84: 'Экранировать пробелы'
        },
        magic_1: 'Ошибка загрузки!',
        magic_2: "Поиск",
        magic_3: "Селекторы",
        magic_4: "Конвертация",
        magic_5: "Авторизация",
        magic_6: "Описание",
        magic_7: "Получить \\ Прочитать код",
        magic_8: "Результаты поиска",
        magic_9: "URL страницы с результатами поиска",
        magic_10: "Открыть",
        magic_11: "Запрос поиска (в параметрах запроса используйте переменную %search%)",
        magic_12: "Конвертировать кириллицу в cp1251",
        magic_13: "POST запрос",
        magic_14: "Основной url",
        magic_15: "Определение страницы авторизации",
        magic_16: "URL страницы входа",
        magic_17: "Открыть",
        magic_18: "Форма входа",
        magic_19: "Выбрать",
        magic_20: "Селекторы",
        magic_21: "Строка в таблице",
        magic_22: "Название категории",
        magic_23: "Ссылка на категорию",
        magic_24: "Добавить основной url",
        magic_25: "Название раздачи",
        magic_26: "Ссылка на раздачу",
        magic_27: "Добавить основной url",
        magic_28: "Размер раздачи",
        magic_29: "Ссылка на скачку раздачи",
        magic_30: "Добавить основной url",
        magic_31: "Количество сидов",
        magic_32: "Количество пиров",
        magic_33: "Дата добавления раздачи",
        magic_34: "Пропустить первые n строк",
        magic_35: "Пропустить последнии n строк",
        magic_36: "Конвертирование",
        magic_37: "Дата добавления раздачи",
        magic_38: "Применить regexp",
        magic_39: "заменить на",
        magic_40: "Заменить название месяца на число",
        magic_41: "Конвертировать время в Unix timestamp из формата",
        magic_42: "Исходная строка",
        magic_43: "Конвертированная",
        magic_44: "Итог",
        magic_45: "Размер торрента",
        magic_46: "Преобразовать",
        magic_47: "Исходная строка",
        magic_48: "Конвертированная",
        magic_49: "Описание торрент-трекера",
        magic_50: "base64 иконка (16x16px)",
        magic_51: "Название торрента",
        magic_52: "Описание торрента",
        magic_53: "Поддержка кириллицы",
        magic_54: "Требуется авторизация",
        magic_55: "Русскоязычный трекер",
        magic_56: "Получить \\ Прочитать код",
        magic_57: "Получить код",
        magic_58: "Прочитать код",
        magic_59: "Сиды",
        magic_60: "Пиры",
        magic_61: "Таблица",
        magic_62: "Атрибут",
        magic_63: "Заменить слова сегодня\\вчера\\сейчас",
        magic_64: "Кодировка страницы"
    };
    if (lang === 'ru') {
        return lang_arr_ru;
    } else {
        return lang_arr_en;
    }
};
if (typeof window === 'undefined') {
    exports.get_lang = get_lang;
}